# Generated by Django 5.0.3 on 2024-03-25 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_store', '0005_shopping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopping',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='shopping',
            name='date_buy',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shopping',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopping',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Book_store.book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopping',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shopping',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
