# Generated by Django 5.0.3 on 2024-04-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_store', '0007_profile_create_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('category', models.ImageField(height_field=500, upload_to='%Y/%m/%d')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='Category', to='Book_store.category'),
        ),
    ]
